[workspace]
members = [
    "2024/day1",
    "2024/day2",
    "2024/day3",
    "2024/day4",
    "2024/day5",
    "2024/day6",
    "2024/day7",
    "2024/day8",
    "2024/day9",
    "2024/day10",
    "2024/day11",
    "2024/day12",
]

[workspace.dependencies]
anyhow = "1.0.93"
clap = "4.5.21"
